apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /Users/davidfox/tfjob-test
        containerPath: /tf-models
    image: kindest/node:v1.23.0
