apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mnist
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-mnist
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard