version: "3.8"

services:
  backend:
    container_name: mnist-classifier
    build: .
    command: ["python", "/opt/model.py", 
            "--train_steps=2", 
            "--log_dir=/logs", "--learning_rate=0.1", "--batch_size=32"]
    volumes:
      - ./tensorboard_logs:/logs
  
