apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  namespace: kubeflow
  name: tfjob-mnist
spec:
  objective:
    type: maximize
    goal: 0.99
    objectiveMetricName: accuracy
  algorithm:
    algorithmName: random
  metricsCollectorSpec:
    source:
      fileSystemPath:
        path: /tensorboard
        kind: Directory
    collector:
      kind: TensorFlowEvent
  parallelTrialCount: 2
  maxTrialCount: 4
  maxFailedTrialCount: 2
  parameters:
    - name: learning_rate
      parameterType: double
      feasibleSpace:
        min: "0.01"
        max: "0.05"
    - name: batch_size
      parameterType: int
      feasibleSpace:
        min: "1"
        max: "3"
  trialTemplate:
    primaryContainerName: tensorflow
    trialParameters:
      - name: learningRate
        description: Learning rate for the training model
        reference: learning_rate
      - name: batchSize
        description: Batch Size
        reference: batch_size
    trialSpec:
      apiVersion: kubeflow.org/v1
      kind: TFJob
      spec:
        tfReplicaSpecs:
          Worker:
            replicas: 1
            template:
              spec:
                containers:
                  - name: tensorflow
                    command:
                    - python
                    - /opt/model.py
                    - --train_steps=2
                    - --log_dir=/tensorflow/tensorboard
                    - "--learning_rate=${trialParameters.learningRate}"
                    - "--batch_size=${trialParameters.batchSize}"
                    - --export_folder=/tensorflow
                    image: foxy7887/mnist-model:v27
                    workingDir: /opt
                    volumeMounts:
                    - mountPath: /tensorflow
                      name: data-volume
                volumes:
                  - name: data-volume
                    persistentVolumeClaim:
                      claimName: pvc-tensorboard
                restartPolicy: Never

