apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- ../workflows

patchesStrategicMerge:
- patches/artifact-repo.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: argo-server
  path: patches/fsgroup-patch.yaml

  