apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: katib
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: apps/katib/overlays/production/
    repoURL: https://github.com/davidfox87/mnist-tfjob-katib.git
    targetRevision: HEAD

  destination:
    server: https://kubernetes.default.svc
    namespace: kubeflow
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true