apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: training-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: my-k8s-test
  source:
    path: apps/training-operator/base
    repoURL: https://github.com/davidfox87/eks-terraform-tfjob-katib-argo.git
    targetRevision: HEAD

  destination:
    server: https://kubernetes.default.svc
    namespace: kubeflow
  syncPolicy:
    automated:
      selfHeal: true
      prune: true