apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

transformers:
- transformers.yaml

patchesJson6902:
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRole
    name: katib-controller
  path: patches/argo-rbac-role-patch.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    name: katib-mysql
    namespace: kubeflow
  path: patches/mysql-securitycontext-gid.yaml


patchesStrategicMerge:
  - patches/katib-controller-args-patch.yaml

