apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo

resources:
- namespace.yaml
- github.com/argoproj/argo-workflows/manifests/cluster-install

patchesStrategicMerge:
- config.yaml

patchesJson6902:
- target:
    version: v1 
    group: apps
    kind: Deployment
    name: argo-server
    namespace: argo
  path: patches/server-patch.yaml

