apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- pvc.yaml
- pv.yaml

transformers:
- transformers.yaml

patchesJson6902:
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRole
    name: katib-controller
  path: patches/argo-rbac-role-patch.yaml

patchesStrategicMerge:
  - patches/katib-controller-args-patch.yaml

