kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-tensorboard
  namespace: kubeflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard