apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- ../workflows


patchesStrategicMerge:
  - |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: workflow-controller-configmap
    data:
      artifactRepository: |    
        archiveLogs: true
        s3:
          endpoint: minio.default:9000
          bucket: my-bucket
          insecure: true
          accessKeySecret:
            name: argo-artifacts
            key: accesskey
          secretKeySecret:
            name: argo-artifacts
            key: secretkey


