apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app: minio
spec:
  type: ClusterIP
  ports:
    - name: minio-console
      port: 9001
      targetPort: 9001
    - name: minio
      port: 9000
      targetPort: 9000
  selector:
    app: minio
