apiVersion: builtin
kind: LabelTransformer
metadata:
  name: my-argo-patch
labels:
  katib.kubeflow.org/metrics-collector-injection: enabled
fieldSpecs:
- kind: Namespace
  metadata: 
    name: kubeflow
  path: metadata/labels
  create: true