apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

patchesJson6902:
  - target: 
      version: v1
      kind: ConfigMap
      name: argocd-cm
    patch: |-
      - op: add
        path: /data
        value: 
            application.resourceTrackingMethod: annotation

namespace: argocd

